/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_guidebee_game_physics_box2d_joints_GearJoint */

#ifndef _Included_com_guidebee_game_physics_box2d_joints_GearJoint
#define _Included_com_guidebee_game_physics_box2d_joints_GearJoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_guidebee_game_physics_box2d_joints_GearJoint
 * Method:    jniGetJoint1
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_guidebee_game_physics_joints_GearJoint_jniGetJoint1
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_guidebee_game_physics_box2d_joints_GearJoint
 * Method:    jniGetJoint2
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_guidebee_game_physics_joints_GearJoint_jniGetJoint2
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_guidebee_game_physics_box2d_joints_GearJoint
 * Method:    jniSetRatio
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_guidebee_game_physics_joints_GearJoint_jniSetRatio
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_guidebee_game_physics_box2d_joints_GearJoint
 * Method:    jniGetRatio
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_guidebee_game_physics_joints_GearJoint_jniGetRatio
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
