/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_guidebee_game_physics_box2d_Joint */

#ifndef _Included_com_guidebee_game_physics_box2d_Joint
#define _Included_com_guidebee_game_physics_box2d_Joint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_guidebee_game_physics_box2d_Joint
 * Method:    jniGetType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_guidebee_game_physics_Joint_jniGetType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_guidebee_game_physics_box2d_Joint
 * Method:    jniGetBodyA
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_guidebee_game_physics_Joint_jniGetBodyA
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_guidebee_game_physics_box2d_Joint
 * Method:    jniGetBodyB
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_guidebee_game_physics_Joint_jniGetBodyB
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_guidebee_game_physics_box2d_Joint
 * Method:    jniGetAnchorA
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_com_guidebee_game_physics_Joint_jniGetAnchorA
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     com_guidebee_game_physics_box2d_Joint
 * Method:    jniGetAnchorB
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_com_guidebee_game_physics_Joint_jniGetAnchorB
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     com_guidebee_game_physics_box2d_Joint
 * Method:    jniGetCollideConnected
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guidebee_game_physics_Joint_jniGetCollideConnected
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_guidebee_game_physics_box2d_Joint
 * Method:    jniGetReactionForce
 * Signature: (JF[F)V
 */
JNIEXPORT void JNICALL Java_com_guidebee_game_physics_Joint_jniGetReactionForce
  (JNIEnv *, jobject, jlong, jfloat, jfloatArray);

/*
 * Class:     com_guidebee_game_physics_box2d_Joint
 * Method:    jniGetReactionTorque
 * Signature: (JF)F
 */
JNIEXPORT jfloat JNICALL Java_com_guidebee_game_physics_Joint_jniGetReactionTorque
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_guidebee_game_physics_box2d_Joint
 * Method:    jniIsActive
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guidebee_game_physics_Joint_jniIsActive
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
