/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_guidebee_game_physics_box2d_ContactImpulse */

#ifndef _Included_com_guidebee_game_physics_box2d_ContactImpulse
#define _Included_com_guidebee_game_physics_box2d_ContactImpulse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_guidebee_game_physics_box2d_ContactImpulse
 * Method:    jniGetNormalImpulses
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_com_guidebee_game_physics_ContactImpulse_jniGetNormalImpulses
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     com_guidebee_game_physics_box2d_ContactImpulse
 * Method:    jniGetTangentImpulses
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_com_guidebee_game_physics_ContactImpulse_jniGetTangentImpulses
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     com_guidebee_game_physics_box2d_ContactImpulse
 * Method:    jniGetCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_guidebee_game_physics_ContactImpulse_jniGetCount
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
