/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_guidebee_game_engine_box2d_api_common_Version */

#ifndef _Included_com_guidebee_game_engine_box2d_api_common_Version
#define _Included_com_guidebee_game_engine_box2d_api_common_Version
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_guidebee_game_engine_box2d_api_common_Version
 * Method:    getVersion
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_guidebee_game_physics_Version_getVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
