/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_guidebee_game_physics_box2d_Manifold */

#ifndef _Included_com_guidebee_game_physics_box2d_Manifold
#define _Included_com_guidebee_game_physics_box2d_Manifold
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_guidebee_game_physics_box2d_Manifold
 * Method:    jniGetType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_guidebee_game_physics_Manifold_jniGetType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_guidebee_game_physics_box2d_Manifold
 * Method:    jniGetPointCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_guidebee_game_physics_Manifold_jniGetPointCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_guidebee_game_physics_box2d_Manifold
 * Method:    jniGetLocalNormal
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_com_guidebee_game_physics_Manifold_jniGetLocalNormal
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     com_guidebee_game_physics_box2d_Manifold
 * Method:    jniGetLocalPoint
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_com_guidebee_game_physics_Manifold_jniGetLocalPoint
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     com_guidebee_game_physics_box2d_Manifold
 * Method:    jniGetPoint
 * Signature: (J[FI)I
 */
JNIEXPORT jint JNICALL Java_com_guidebee_game_physics_Manifold_jniGetPoint
  (JNIEnv *, jobject, jlong, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_guidebee_game_physics_box2d_Manifold_ManifoldPoint */

#ifndef _Included_com_guidebee_game_physics_box2d_Manifold_ManifoldPoint
#define _Included_com_guidebee_game_physics_box2d_Manifold_ManifoldPoint
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_guidebee_game_physics_box2d_Manifold_ManifoldType */

#ifndef _Included_com_guidebee_game_physics_box2d_Manifold_ManifoldType
#define _Included_com_guidebee_game_physics_box2d_Manifold_ManifoldType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
